### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by flokX** [flokX/devShort#5]
Here's a roadmap for the next version:

- [x] Stop the visible redirection to the redirect.php file, this looks better at example when a 404 error occurs (link.example.com/redirect.php?short=Link1 to link.example.com/Link1).
- [x] Make it possible to add also shortlinks with special characters like _?_ or filter them in the web panel (Issue: #6)
- [X] Constant libary updates when a new version is there
- [x] Redesign admin interface (PR: #12)
